spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user_center?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 159753
  application:
    name: usercenter-core-service
  redis:
    host: 192.168.174.128
    port: 6379
    jedis:
      pool:
        max-wait: -1ms
        max-active: 8
        max-idle: 8
dubbo:
  registry:
    address: 192.168.174.128:2181
    protocol: zookeeper
    check: false
    timeout: 10000
  protocol:
    name: dubbo
    port: 30004
server:
  port: 8080
user-center:
  common:
    redis-prefix: ucenter_



